#!/bin/bash
# This application accepts a Shotcut mlt xml file as an input. As an output the script will use the information of the xml to edit the input using codec copy to produce an output that losslessly copies select frames.
version=0.1
file=$(xml sel -t -m "//mlt/producer[@id='producer0']" -v "property[@name='resource']" -n "$1")
in=$(xml sel -t -m "//mlt/playlist[@id='playlist0']/entry" -v @in -n "$1" | sort -u | xargs | sed 's/ /,/g')
echo $file
echo ${in%?}
logdir=$(dirname $file)
export FFREPORT="file=${logdir}/%p_%t_$(basename "$0")_${version}.txt"
ffmpeg -i "${file}" -map 0:v -map 0:a -c:v copy -c:a copy -f segment -segment_times "${in%?}" "${file%.*}_%03d.mov"
